#!/bin/sh

### BEGIN INIT INFO
# PROVIDES:         lumos
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Lumos
# Description:      Lumos
### END INIT INFO

DAEMON=/usr/local/bin/lumos.py
DAEMON_NAME=lumos       # The name of this file
PIDFILE=/var/run/$DAEMON_NAME.pid
DAEMON_USER=root

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting lumos.py"
    start-stop-daemon --start --background --quiet --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --exec $DAEMON
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping lumos.py"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
